#!/data/data/com.termux/files/usr/bin/sh
set -e -u

SCRIPTNAME=termux-bluetooth-scan
show_usage () {
    echo "Usage: $SCRIPTNAME"
    echo "Scan for bluetooth devices"
    exit 0
}

FREQUENCY=""
while getopts :h: option
do
    case "$option" in
	h) show_usage;;
    esac
done
shift $(($OPTIND-1))

if [ $# != 0 ]; then echo "$SCRIPTNAME: too many arguments"; exit 1; fi

PARAMS=""
/data/data/com.termux/files/usr/libexec/termux-api BluetoothScan $PARAMS
